{{- $previewGatewayEnabled := .Values.previewGateway.enabled | default false -}}
{{- $previewGatewayBaseDomain := .Values.previewGateway.baseDomain | default "" -}}
{{- $previewGatewayName := printf "%s-preview-gateway" (include "appstudio.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- if and $previewGatewayEnabled (ne (trim $previewGatewayBaseDomain) "") .Values.previewGateway.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default $previewGatewayName .Values.previewGateway.serviceAccount.name }}
  labels:
    {{- include "appstudio.labels" . | nindent 4 }}
{{- end }}
