{{- $previewGatewayEnabled := .Values.previewGateway.enabled | default false -}}
{{- $previewGatewayBaseDomain := .Values.previewGateway.baseDomain | default "" -}}
{{- $previewGatewayName := printf "%s-preview-gateway" (include "appstudio.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- $previewGatewayServiceAccountName := ternary (default $previewGatewayName .Values.previewGateway.serviceAccount.name) (default "default" .Values.previewGateway.serviceAccount.name) (.Values.previewGateway.serviceAccount.create) -}}
{{- if and $previewGatewayEnabled (ne (trim $previewGatewayBaseDomain) "") .Values.previewGateway.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $previewGatewayName }}
  labels:
    {{- include "appstudio.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $previewGatewayName }}
  labels:
    {{- include "appstudio.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $previewGatewayServiceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $previewGatewayName }}
{{- end }}
