import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const app = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
const dialog = await readFile(new URL('./ProjectShareDialog.vue', import.meta.url), 'utf8')

test('keeps Production inside Project Settings and removes the standalone workbench surface', () => {
  assert.match(app, /type ProjectSettingsPane = 'project' \| 'production' \| 'model'/)
  assert.match(app, /projectSettingsPanes/)
  assert.match(app, /aria-label="Project Settings sections"/)
  assert.match(app, /:id="`project-settings-tab-\$\{pane\[0\]\}`"/)
  assert.match(app, /aria-labelledby="project-settings-tab-project"/)
  assert.match(app, /aria-labelledby="project-settings-tab-production"/)
  assert.match(app, /settingsProject \? 'project-settings-tab-model' : undefined/)
  assert.match(app, /projectSettingsPane === 'production'/)
  assert.match(app, /id="project-settings-pane-production"/)
  assert.doesNotMatch(app, /id: 'builtin:production'/)
  assert.doesNotMatch(app, /builtInTab: 'production'/)
  assert.doesNotMatch(app, /activeWorkbenchTab\?\.kind === 'production'/)
  assert.doesNotMatch(app, /kind: 'production'/)
  assert.doesNotMatch(app, /builtInTab: 'publishing'/)
  assert.doesNotMatch(app, /title: 'Publishing'/)
  assert.doesNotMatch(app, /activeWorkbenchTab\?\.kind === 'publishing'/)
})

test('keeps the plus in the scrolling tab strip and exposes a solid Share anchor', () => {
  const headerStart = app.indexOf('<header class="flex h-14')
  const panelStart = app.indexOf('<div\n        v-if="activeWorkbenchTab?.kind === \'launcher\'"', headerStart)
  assert.ok(headerStart >= 0 && panelStart > headerStart)
  const header = app.slice(headerStart, panelStart)
  const tablistStart = header.indexOf('role="tablist"')
  const tablistEnd = header.indexOf('</div>\n        <button', tablistStart)
  const plusStart = header.indexOf('aria-label="New tab"')
  const shareStart = header.indexOf('aria-label="Share project"')
  assert.ok(tablistStart >= 0 && tablistEnd > tablistStart && plusStart > tablistEnd && shareStart > plusStart)
  const tablist = header.slice(tablistStart, tablistEnd)
  assert.doesNotMatch(tablist, /aria-label="New tab"/)
  assert.match(header, /max-w-\[15rem\] shrink[^\n]*items-center/)
  assert.match(header, /aria-label="New tab"[\s\S]*@click="openWorkbenchLauncher"/)
  assert.match(header, /ref="shareButtonRef"/)
  assert.match(header, /@click="openShareDialog"/)
  assert.match(header, />\s*<span>Share<\/span>/)
  assert.match(header, /border-accent bg-accent/)
})

test('keeps Production focused on deployment and technical details inside Settings', () => {
  const productionStart = app.indexOf('id="project-settings-pane-production"')
  const productionEnd = app.indexOf('id="project-settings-pane-model"', productionStart)
  assert.ok(productionStart >= 0 && productionEnd > productionStart)
  const pane = app.slice(productionStart, productionEnd)
  assert.match(pane, /aria-label="Production overview"/)
  assert.match(pane, /Redeploy/)
  assert.match(pane, /Open app/)
  assert.match(pane, /aria-label="Technical details"/)
  assert.match(pane, /Redeploy updates the production deployment only\. It does not publish or change access\./)
  assert.match(pane, /Publication is ready/)
  assert.match(pane, /bg-success-subtle[^\n]*text-success/)
  assert.match(pane, /publishing\?\.publication\?\.error && !publishing\?\.publication\?\.ready/)
  assert.match(pane, /publishingActionError[^\n]*text-danger/)
  // Visibility is a first-class pane control: an inline select that applies
  // immediately in every published state (Live and converging), so flipping
  // public/invite-only never requires opening the dialog. Grants, invites,
  // and disable stay behind the Share-dialog entry point.
  const visibilitySelects = pane.match(/aria-label="Production visibility"/g) ?? []
  assert.equal(visibilitySelects.length, 2)
  assert.match(pane, /@change="onProductionVisibilityChange"/)
  assert.match(pane, /option value="restricted">Invite-only/)
  assert.match(pane, /option value="public">Public — anyone with the link/)
  assert.match(pane, /Manage access/)
  assert.match(pane, /@click="openShareDialog"/)
  assert.doesNotMatch(pane, /Disable access/)
  assert.doesNotMatch(pane, /role="radiogroup"/)
  assert.doesNotMatch(pane, /@click="publishCurrentProject"/)
})

test('treats a ready publication without a URL as calm success while Live remains URL-dependent', () => {
  assert.match(app, /const productionPublicationReady = computed\(\(\) => Boolean\(publishing\.value\?\.published && publishing\.value\.publication\?\.ready\)\)/)
  assert.match(app, /return \{ label: productionURL\.value \? 'Live' : 'Ready', tone: 'success' as const \}/)
  assert.match(app, /productionPublicationReady\.value && !productionURL\.value/)
  assert.match(app, /const productionPublicationStatus = computed\(\(\) => \{[\s\S]*if \(productionPublicationReady\.value\)[\s\S]*tone: 'success'/)
  assert.match(app, /if \(publishing\.value\?\.publication\?\.error\) return \{ label: 'Error', tone: 'danger' as const \}/)
  const overviewStart = app.indexOf('const productionOverview = computed')
  const overviewEnd = app.indexOf('const productionOverviewDescription = computed', overviewStart)
  assert.ok(overviewStart >= 0 && overviewEnd > overviewStart)
  assert.match(app.slice(overviewStart, overviewEnd), /productionPublicationReady\.value[\s\S]*publishing\.value\.publication\?\.error/)
  assert.match(app, /The publication is ready; the production link is still being resolved\./)
})

test('routes sharing through the modular dialog and current access contracts only', () => {
  assert.match(app, /import ProjectShareDialog from '\.\/ProjectShareDialog\.vue'/)
  assert.match(app, /<ProjectShareDialog[\s\S]*v-model:mode="shareMode"[\s\S]*@save="publishCurrentProject"[\s\S]*@grant="grantCurrentProjectAccess"[\s\S]*@invite="inviteCurrentProjectAccess"[\s\S]*@revoke="revokeCurrentProjectAccess"[\s\S]*@disable="unpublishCurrentProject"/)
  assert.match(app, /@open-production-settings="openProductionSettingsFromShare"/)
  assert.match(app, /api\.publishProject\(props\.ctx, name, shareMode\.value\)/)
  assert.match(dialog, /General access/)
  assert.match(dialog, /value="restricted">Restricted/)
  assert.match(dialog, /value="public">Anyone with the link/)
  assert.match(dialog, /People with access/)
  assert.match(dialog, /availableMembers/)
  assert.match(dialog, /activeGrants/)
  assert.match(dialog, /savedRestricted/)
  assert.match(dialog, /canAddMember/)
  assert.match(dialog, /Save Restricted access before adding viewers\./)
  assert.match(dialog, /const canSave = computed\(\(\) => \(/)
  assert.match(dialog, /Copy production link/)
  assert.match(dialog, /Copy link/)
  assert.match(dialog, /open-production-settings/)
  assert.match(dialog, /Production settings/)
  assert.match(dialog, /Done/)
  assert.match(dialog, /Save access/)
  assert.match(dialog, /Publish app/)
  assert.match(dialog, /Revoke/)
  assert.match(dialog, /Disable access/)
  assert.match(dialog, /dialogCloseButton/)
  assert.match(dialog, /focusDialog/)
  for (const inventedCapability of ['owner', 'group']) {
    assert.doesNotMatch(dialog, new RegExp(`\\b${inventedCapability}\\b`, 'i'))
  }
  // Email appears ONLY as the explicit invite affordance (pre-provisioned
  // pending user, adopted at first sign-in) — grants themselves are still
  // written against stable User names, never email identities.
  assert.match(dialog, /canInvite/)
  assert.match(dialog, /emit\('invite', email\)/)
  assert.match(dialog, /Invite by email — new users join at first sign-in/)
  assert.doesNotMatch(dialog, /member\.role|grant\.role|role\s*:/i)
})

test('suppresses stale publication errors for a ready URL and keeps Copy link in the modal footer', () => {
  assert.match(dialog, /published && publication\?\.ready/)
  assert.match(dialog, /bg-success-subtle[^\n]*text-success[^\n]*role="status"/)
  assert.match(dialog, /Publication is ready; the production link is still being resolved\./)
  assert.match(dialog, /v-else-if="published && publication\?\.error"[^>]*text-danger[^>]*role="alert"/)
  assert.match(dialog, /v-if="error"[^>]*text-danger/)
  const footerStart = dialog.indexOf('<footer')
  const copyStart = dialog.indexOf('aria-label="Copy production link"')
  assert.ok(footerStart >= 0 && copyStart > footerStart)
  assert.match(dialog.slice(copyStart, copyStart + 240), /:disabled="!link \|\| busy \|\| loading"/)
  assert.match(dialog, /await navigator\.clipboard\.writeText\(link\.value\)/)
  assert.match(dialog, /Link copied\./)
  assert.match(dialog, /Copy is unavailable in this browser\./)
})

test('published apps can change access anytime; only first publish waits for production readiness', () => {
  // An access flip on a promoted app is an intent write — a rolling or
  // briefly-unready deployment must not block it (the publication state
  // machine reports Pending honestly while the gate converges).
  assert.match(dialog, /!props\.loading && !props\.busy && \(props\.published \|\| props\.productionReady\)/)
  // The deploy-first warning is reserved for never-promoted projects.
  assert.match(dialog, /v-if="!published && !productionReady"/)
  assert.match(dialog, /const modeDirty = computed\(\(\) => props\.published && selectedMode\.value !== initialMode\.value\)/)
  assert.match(dialog, /const canAddMember = computed\(\(\) => \(\s*savedRestricted\.value && !modeDirty\.value/s)
})

test('restores the Share trigger after confirmed disable and uses one production-surface polling transition', () => {
  const unpublishStart = app.indexOf('async function unpublishCurrentProject')
  const unpublishEnd = app.indexOf('async function grantCurrentProjectAccess', unpublishStart)
  assert.ok(unpublishStart >= 0 && unpublishEnd > unpublishStart)
  const unpublish = app.slice(unpublishStart, unpublishEnd)
  assert.match(unpublish, /let disableSucceeded = false/)
  assert.match(unpublish, /publishingActionBusy\.value = false[\s\S]*if \(disableSucceeded\) closeShareDialog\(\)/)
  assert.doesNotMatch(unpublish, /shareDialogOpen\.value = false/)

  assert.match(app, /const productionSurfaceActive = computed\(\(\) => productionSettingsVisible\.value \|\| shareDialogOpen\.value\)/)
  const watcherStart = app.indexOf('watch(\n  () => [productionSurfaceActive.value')
  const watcherEnd = app.indexOf('\n\n onBeforeUnmount', watcherStart)
  assert.ok(watcherStart >= 0)
  const watcher = app.slice(watcherStart, watcherEnd > watcherStart ? watcherEnd : watcherStart + 1800)
  assert.match(watcher, /surfaceOrProjectChanged/)
  assert.match(watcher, /clearPromotionPoll\(\)/)
  assert.match(watcher, /clearPublishingPoll\(\)/)
  assert.doesNotMatch(watcher, /kind === 'publishing'/)
  const openStart = app.indexOf('function openShareDialog')
  const openEnd = app.indexOf('function closeShareDialog', openStart)
  assert.ok(openStart >= 0 && openEnd > openStart)
  assert.doesNotMatch(app.slice(openStart, openEnd), /loadPromotion|loadPublishing/)

  const settingsStart = app.indexOf('function openProductionSettingsFromShare')
  const settingsEnd = app.indexOf('function resetWorkbench', settingsStart)
  assert.ok(settingsStart >= 0 && settingsEnd > settingsStart)
  const settingsHandler = app.slice(settingsStart, settingsEnd)
  assert.match(settingsHandler, /shareDialogOpen\.value = false/)
  assert.match(settingsHandler, /projectSettingsPane\.value = 'production'/)
  assert.match(settingsHandler, /openBuiltInWorkbenchTab\('settings'\)/)
  assert.match(settingsHandler, /productionSettingsPaneRef\.value\?\.focus\(\)/)
  assert.doesNotMatch(settingsHandler, /shareButtonRef/)

  const closeStart = app.indexOf('function closeShareDialog')
  const closeEnd = app.indexOf('function openProductionSettingsFromShare', closeStart)
  assert.ok(closeStart >= 0 && closeEnd > closeStart)
  const closeHandler = app.slice(closeStart, closeEnd)
  assert.match(closeHandler, /shareDialogOpen\.value = false[\s\S]*if \(!productionSettingsVisible\.value\)/)
  assert.doesNotMatch(closeHandler, /kind !== 'production'/)
})

test('layers the shared confirm dialog at body and restores Disable access focus on cancel', () => {
  const pkDialogStart = app.indexOf('<PkConfirmDialog />')
  const shareStart = app.indexOf('<ProjectShareDialog')
  assert.ok(pkDialogStart >= 0 && shareStart > pkDialogStart)
  assert.match(app.slice(Math.max(0, pkDialogStart - 80), pkDialogStart + 40), /<Teleport to="body">[\s\S]*<PkConfirmDialog \/>/)

  const unpublishStart = app.indexOf('async function unpublishCurrentProject')
  const unpublishEnd = app.indexOf('async function grantCurrentProjectAccess', unpublishStart)
  assert.ok(unpublishStart >= 0 && unpublishEnd > unpublishStart)
  const unpublish = app.slice(unpublishStart, unpublishEnd)
  assert.match(unpublish, /const disableAccessTrigger = document\.activeElement instanceof HTMLElement \? document\.activeElement : null/)
  assert.match(unpublish, /const confirmed = await confirmDialog\(/)
  assert.match(unpublish, /if \(!confirmed\) \{[\s\S]*await nextTick\(\)[\s\S]*disableAccessTrigger\?\.isConnected[\s\S]*disableAccessTrigger\.focus\(\)[\s\S]*return/)
})
