//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectEnvironmentSpec) DeepCopyInto(out *ProjectEnvironmentSpec) {
	*out = *in
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]ProjectProviderBindingSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectEnvironmentSpec.
func (in *ProjectEnvironmentSpec) DeepCopy() *ProjectEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectEnvironmentStatus) DeepCopyInto(out *ProjectEnvironmentStatus) {
	*out = *in
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]ProjectProviderBindingStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectEnvironmentStatus.
func (in *ProjectEnvironmentStatus) DeepCopy() *ProjectEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectMemory) DeepCopyInto(out *ProjectMemory) {
	*out = *in
	if in.Goals != nil {
		in, out := &in.Goals, &out.Goals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectMemory.
func (in *ProjectMemory) DeepCopy() *ProjectMemory {
	if in == nil {
		return nil
	}
	out := new(ProjectMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectMessage) DeepCopyInto(out *ProjectMessage) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectMessage.
func (in *ProjectMessage) DeepCopy() *ProjectMessage {
	if in == nil {
		return nil
	}
	out := new(ProjectMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectProviderBindingSpec) DeepCopyInto(out *ProjectProviderBindingSpec) {
	*out = *in
	if in.ResourceRef != nil {
		in, out := &in.ResourceRef, &out.ResourceRef
		*out = new(ProjectProviderResourceReference)
		**out = **in
	}
	in.Values.DeepCopyInto(&out.Values)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectProviderBindingSpec.
func (in *ProjectProviderBindingSpec) DeepCopy() *ProjectProviderBindingSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectProviderBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectProviderBindingStatus) DeepCopyInto(out *ProjectProviderBindingStatus) {
	*out = *in
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectProviderBindingStatus.
func (in *ProjectProviderBindingStatus) DeepCopy() *ProjectProviderBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectProviderBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectProviderResourceReference) DeepCopyInto(out *ProjectProviderResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectProviderResourceReference.
func (in *ProjectProviderResourceReference) DeepCopy() *ProjectProviderResourceReference {
	if in == nil {
		return nil
	}
	out := new(ProjectProviderResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectRepositoryBinding) DeepCopyInto(out *ProjectRepositoryBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectRepositoryBinding.
func (in *ProjectRepositoryBinding) DeepCopy() *ProjectRepositoryBinding {
	if in == nil {
		return nil
	}
	out := new(ProjectRepositoryBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSharingPolicy) DeepCopyInto(out *ProjectSharingPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSharingPolicy.
func (in *ProjectSharingPolicy) DeepCopy() *ProjectSharingPolicy {
	if in == nil {
		return nil
	}
	out := new(ProjectSharingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSharingSpec) DeepCopyInto(out *ProjectSharingSpec) {
	*out = *in
	out.Preview = in.Preview
	out.Publishing = in.Publishing
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSharingSpec.
func (in *ProjectSharingSpec) DeepCopy() *ProjectSharingSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSharingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(ProjectRepositoryBinding)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(ProjectTemplateSpec)
		**out = **in
	}
	in.Memory.DeepCopyInto(&out.Memory)
	out.Sharing = in.Sharing
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]ProjectEnvironmentSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]ProjectEnvironmentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectTemplateSpec) DeepCopyInto(out *ProjectTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectTemplateSpec.
func (in *ProjectTemplateSpec) DeepCopy() *ProjectTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
