apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: ai.kedge.faros.sh
spec:
  resources:
  - group: ai.kedge.faros.sh
    name: projects
    schema: v260625-49a11a87.projects.ai.kedge.faros.sh
    storage:
      crd: {}
status: {}
