apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: ai.kedge.faros.sh
spec:
  resources:
  - group: ai.kedge.faros.sh
    name: projects
    schema: v260808-50d90fba.projects.ai.kedge.faros.sh
    storage:
      crd: {}
  - group: ai.kedge.faros.sh
    name: sessions
    schema: v260806-59f3b567.sessions.ai.kedge.faros.sh
    storage:
      crd: {}
  - group: ai.kedge.faros.sh
    name: studios
    schema: v260809-dbe6b457.studios.ai.kedge.faros.sh
    storage:
      crd: {}
status: {}
