/*
Copyright 2026 The Faros Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package api

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/google/uuid"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"

	aiv1alpha1 "github.com/faroshq/provider-app-studio/apis/ai/v1alpha1"
	asclient "github.com/faroshq/provider-app-studio/client"
)

const (
	codeProviderGroupVersion = "code.kedge.faros.sh/v1alpha1"

	projectRepositoryRefAnnotation        = "app-studio.ai.kedge.faros.sh/repository-ref"
	projectRepositoryNameAnnotation       = "app-studio.ai.kedge.faros.sh/repository-name"
	projectRepositoryConnectionAnnotation = "app-studio.ai.kedge.faros.sh/repository-connection"
	projectRepositoryProjectAnnotation    = "app-studio.ai.kedge.faros.sh/project"

	projectRepositoryProjectLabel = "app-studio.ai.kedge.faros.sh/project"
	codeRepositoryLabel           = "code.kedge.faros.sh/repository"

	projectRepositoryStatusReady             = "Ready"
	projectRepositoryStatusProvisioning      = "Provisioning"
	projectRepositoryStatusRepositoryMissing = "RepositoryMissing"
	projectRepositoryStatusConnectionMissing = "ConnectionMissing"
	projectRepositoryStatusUnavailable       = "Unavailable"
)

var (
	codeConnectionsGVR       = schema.GroupVersionResource{Group: "code.kedge.faros.sh", Version: "v1alpha1", Resource: "connections"}
	codeRepositoriesGVR      = schema.GroupVersionResource{Group: "code.kedge.faros.sh", Version: "v1alpha1", Resource: "repositories"}
	codeRepositoryCommitsGVR = schema.GroupVersionResource{Group: "code.kedge.faros.sh", Version: "v1alpha1", Resource: "repositorycommits"}
)

type projectRepositoryPlan struct {
	Ref           string
	Name          string
	ConnectionRef string
	Description   string
}

type codeResourceGetter func(ctx context.Context, gvr schema.GroupVersionResource, name string) (*unstructured.Unstructured, error)
type codeResourceLister func(ctx context.Context, gvr schema.GroupVersionResource, opts metav1.ListOptions) (*unstructured.UnstructuredList, error)

func (p projectRepositoryPlan) projectAnnotations() map[string]string {
	return map[string]string{
		projectRepositoryRefAnnotation:        p.Ref,
		projectRepositoryNameAnnotation:       p.Name,
		projectRepositoryConnectionAnnotation: p.ConnectionRef,
	}
}

func (s *Server) prepareProjectRepository(ctx context.Context, c *asclient.Client, requestedConnection, requestedRepoName, displayName, description string) (projectRepositoryPlan, error) {
	connectionRef, err := selectCodeConnection(ctx, c, requestedConnection)
	if err != nil {
		return projectRepositoryPlan{}, err
	}
	repoName, err := repositoryName(ctx, c, requestedRepoName, displayName)
	if err != nil {
		return projectRepositoryPlan{}, err
	}
	if strings.TrimSpace(description) == "" {
		description = "Generated by App Studio for " + displayName
	}
	return projectRepositoryPlan{
		Ref:           repoName,
		Name:          repoName,
		ConnectionRef: connectionRef,
		Description:   description,
	}, nil
}

func selectCodeConnection(ctx context.Context, c *asclient.Client, requested string) (string, error) {
	if requested != "" {
		conn, err := c.Dynamic().Resource(codeConnectionsGVR).Get(ctx, requested, metav1.GetOptions{})
		if err != nil {
			return "", codeProviderRequestError("get Code connection", err)
		}
		if !unstructuredConditionTrue(conn, "Validated") {
			return "", newValidationError(fmt.Sprintf("Code connection %q is not validated yet", requested))
		}
		return requested, nil
	}

	list, err := c.Dynamic().Resource(codeConnectionsGVR).List(ctx, metav1.ListOptions{})
	if err != nil {
		return "", codeProviderRequestError("list Code connections", err)
	}
	sort.Slice(list.Items, func(i, j int) bool {
		return list.Items[i].GetName() < list.Items[j].GetName()
	})
	for i := range list.Items {
		if unstructuredConditionTrue(&list.Items[i], "Validated") {
			return list.Items[i].GetName(), nil
		}
	}
	if len(list.Items) == 0 {
		return "", newValidationError("You need to connect to a Git account before you can continue")
	}
	return "", newValidationError("wait for a Code connection to validate before creating an App Studio project")
}

func repositoryName(ctx context.Context, c *asclient.Client, requested, displayName string) (string, error) {
	base := dns1123Label(requested)
	if base == "" {
		base = dns1123Label(displayName)
	}
	if base == "" {
		base = "app"
	}
	for i := 0; i < 5; i++ {
		name := base
		if i > 0 {
			name = dns1123LabelWithSuffix(base, uuid.NewString()[:6])
		}
		if _, err := c.Dynamic().Resource(codeRepositoriesGVR).Get(ctx, name, metav1.GetOptions{}); apierrors.IsNotFound(err) {
			return name, nil
		} else if err != nil {
			return "", codeProviderRequestError("get Code repository", err)
		}
	}
	return dns1123LabelWithSuffix(base, uuid.NewString()[:8]), nil
}

func (s *Server) createProjectRepository(ctx context.Context, c *asclient.Client, projectName string, plan projectRepositoryPlan) error {
	repo := &unstructured.Unstructured{}
	repo.SetAPIVersion(codeProviderGroupVersion)
	repo.SetKind("Repository")
	repo.SetName(plan.Ref)
	repo.SetLabels(map[string]string{
		projectRepositoryProjectLabel: projectName,
	})
	repo.SetAnnotations(map[string]string{
		projectRepositoryProjectAnnotation: projectName,
	})
	repo.Object["spec"] = map[string]any{
		"connectionRef": plan.ConnectionRef,
		"name":          plan.Name,
		"visibility":    "private",
		"description":   plan.Description,
		"autoInit":      true,
	}
	if _, err := c.Dynamic().Resource(codeRepositoriesGVR).Create(ctx, repo, metav1.CreateOptions{}); err != nil {
		if apierrors.IsAlreadyExists(err) {
			return newValidationError(fmt.Sprintf("Code repository %q already exists", plan.Ref))
		}
		return codeProviderRequestError("create Code repository", err)
	}
	return nil
}

func projectRepositoryView(ctx context.Context, c *asclient.Client, p *aiv1alpha1.Project) *ProjectRepositoryView {
	var get codeResourceGetter
	var list codeResourceLister
	if c != nil {
		get = func(ctx context.Context, gvr schema.GroupVersionResource, name string) (*unstructured.Unstructured, error) {
			return c.Dynamic().Resource(gvr).Get(ctx, name, metav1.GetOptions{})
		}
		list = func(ctx context.Context, gvr schema.GroupVersionResource, opts metav1.ListOptions) (*unstructured.UnstructuredList, error) {
			return c.Dynamic().Resource(gvr).List(ctx, opts)
		}
	}
	return projectRepositoryViewFromResources(ctx, p, get, list)
}

func projectRepositoryViewFromGetter(ctx context.Context, p *aiv1alpha1.Project, get codeResourceGetter) *ProjectRepositoryView {
	return projectRepositoryViewFromResources(ctx, p, get, nil)
}

func projectRepositoryViewFromResources(ctx context.Context, p *aiv1alpha1.Project, get codeResourceGetter, list codeResourceLister) *ProjectRepositoryView {
	annotations := p.GetAnnotations()
	ref := strings.TrimSpace(annotations[projectRepositoryRefAnnotation])
	if ref == "" {
		return nil
	}
	view := &ProjectRepositoryView{
		Ref:           ref,
		Name:          strings.TrimSpace(annotations[projectRepositoryNameAnnotation]),
		ConnectionRef: strings.TrimSpace(annotations[projectRepositoryConnectionAnnotation]),
		Status:        projectRepositoryStatusProvisioning,
	}
	if get == nil {
		return view
	}
	repo, err := get(ctx, codeRepositoriesGVR, ref)
	if err != nil {
		if apierrors.IsNotFound(err) {
			view.Status = projectRepositoryStatusRepositoryMissing
			view.Message = fmt.Sprintf("Repository resource %q no longer exists.", ref)
			return view
		}
		view.Status = projectRepositoryStatusUnavailable
		view.Message = fmt.Sprintf("Could not read repository resource %q.", ref)
		return view
	}
	if name, _, _ := unstructured.NestedString(repo.Object, "spec", "name"); name != "" {
		view.Name = name
	}
	if connectionRef, _, _ := unstructured.NestedString(repo.Object, "spec", "connectionRef"); connectionRef != "" {
		view.ConnectionRef = connectionRef
	}
	view.HTMLURL, _, _ = unstructured.NestedString(repo.Object, "status", "htmlURL")
	if view.ConnectionRef == "" {
		view.Status = projectRepositoryStatusConnectionMissing
		view.Message = fmt.Sprintf("Repository resource %q does not reference a Code connection.", ref)
		return view
	}
	if _, err := get(ctx, codeConnectionsGVR, view.ConnectionRef); err != nil {
		if apierrors.IsNotFound(err) {
			view.Status = projectRepositoryStatusConnectionMissing
			view.Message = fmt.Sprintf("Connection resource %q no longer exists.", view.ConnectionRef)
			return view
		}
		view.Status = projectRepositoryStatusUnavailable
		view.Message = fmt.Sprintf("Could not read connection resource %q.", view.ConnectionRef)
		return view
	}
	view.Ready = unstructuredConditionTrue(repo, "Ready")
	if view.Ready {
		view.Status = projectRepositoryStatusReady
	}
	view.Commits = projectRepositoryCommits(ctx, list, ref)
	return view
}

func projectRepositoryCommits(ctx context.Context, list codeResourceLister, repositoryRef string) []ProjectRepositoryCommitView {
	if list == nil || strings.TrimSpace(repositoryRef) == "" {
		return nil
	}
	selector := labels.SelectorFromSet(labels.Set{codeRepositoryLabel: repositoryRef}).String()
	items, err := list(ctx, codeRepositoryCommitsGVR, metav1.ListOptions{LabelSelector: selector})
	if err != nil {
		return nil
	}
	commits := make([]ProjectRepositoryCommitView, 0, len(items.Items))
	for i := range items.Items {
		view := projectRepositoryCommitView(&items.Items[i])
		if view.Name != "" {
			commits = append(commits, view)
		}
	}
	sort.Slice(commits, func(i, j int) bool {
		return commits[i].CreatedAt.After(commits[j].CreatedAt)
	})
	if len(commits) > 20 {
		commits = commits[:20]
	}
	return commits
}

func projectRepositoryCommitView(obj *unstructured.Unstructured) ProjectRepositoryCommitView {
	view := ProjectRepositoryCommitView{
		Name:      obj.GetName(),
		CreatedAt: obj.GetCreationTimestamp().Time,
	}
	view.Phase, _, _ = unstructured.NestedString(obj.Object, "status", "phase")
	view.Branch, _, _ = unstructured.NestedString(obj.Object, "status", "branch")
	view.CommitSHA, _, _ = unstructured.NestedString(obj.Object, "status", "commitSHA")
	view.CommitURL, _, _ = unstructured.NestedString(obj.Object, "status", "commitURL")
	view.Message, _, _ = unstructured.NestedString(obj.Object, "spec", "message")
	if count, ok, _ := unstructured.NestedInt64(obj.Object, "status", "source", "fileCount"); ok {
		view.FileCount = count
	} else if files, ok, _ := unstructured.NestedSlice(obj.Object, "status", "files"); ok {
		view.FileCount = int64(len(files))
	}
	if completed, ok, _ := unstructured.NestedString(obj.Object, "status", "completedAt"); ok && completed != "" {
		if t, err := time.Parse(time.RFC3339, completed); err == nil {
			view.CompletedAt = &t
		}
	}
	return view
}

func codeProviderRequestError(op string, err error) error {
	if err == nil {
		return nil
	}
	msg := strings.ToLower(err.Error())
	if strings.Contains(msg, "server could not find the requested resource") ||
		strings.Contains(msg, "the server doesn't have a resource type") {
		return newValidationError("enable the Code provider before creating App Studio projects")
	}
	return fmt.Errorf("%s: %w", op, err)
}

func unstructuredConditionTrue(obj *unstructured.Unstructured, condType string) bool {
	conds, found, _ := unstructured.NestedSlice(obj.Object, "status", "conditions")
	if !found {
		return false
	}
	for _, raw := range conds {
		cond, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		if cond["type"] == condType && cond["status"] == string(metav1.ConditionTrue) {
			return true
		}
	}
	return false
}

func dns1123Label(str string) string {
	return slugifyProjectName(str)
}

func dns1123LabelWithSuffix(base, suffix string) string {
	suffix = dns1123Label(suffix)
	if suffix == "" {
		suffix = uuid.NewString()[:6]
	}
	maxBase := 63 - len(suffix) - 1
	if maxBase < 1 {
		maxBase = 1
	}
	if len(base) > maxBase {
		base = strings.Trim(base[:maxBase], "-")
	}
	if base == "" {
		base = "app"
	}
	return base + "-" + suffix
}
